//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 20.06.2009 12:50:47
namespace ServerLib.Data
{
    
    /// <summary>
    /// There are no comments for DatabaseEntities in the schema.
    /// </summary>
    public partial class DatabaseEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new DatabaseEntities object using the connection string found in the 'DatabaseEntities' section of the application configuration file.
        /// </summary>
        public DatabaseEntities() : 
                base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(string connectionString) : 
                base(connectionString, "DatabaseEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "DatabaseEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for DbEntrySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<DbEntry> DbEntrySet
        {
            get
            {
                if ((this._DbEntrySet == null))
                {
                    this._DbEntrySet = base.CreateQuery<DbEntry>("[DbEntrySet]");
                }
                return this._DbEntrySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<DbEntry> _DbEntrySet;
        /// <summary>
        /// There are no comments for DbUserSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<DbUser> DbUserSet
        {
            get
            {
                if ((this._DbUserSet == null))
                {
                    this._DbUserSet = base.CreateQuery<DbUser>("[DbUserSet]");
                }
                return this._DbUserSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<DbUser> _DbUserSet;
        /// <summary>
        /// There are no comments for DbEntrySet in the schema.
        /// </summary>
        public void AddToDbEntrySet(DbEntry dbEntry)
        {
            base.AddObject("DbEntrySet", dbEntry);
        }
        /// <summary>
        /// There are no comments for DbUserSet in the schema.
        /// </summary>
        public void AddToDbUserSet(DbUser dbUser)
        {
            base.AddObject("DbUserSet", dbUser);
        }
    }
    /// <summary>
    /// There are no comments for DatabaseModel.DbEntry in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="DbEntry")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class DbEntry : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new DbEntry object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="dateFrom">Initial value of DateFrom.</param>
        /// <param name="userId">Initial value of UserId.</param>
        public static DbEntry CreateDbEntry(long id, string title, global::System.DateTime dateFrom, long userId)
        {
            DbEntry dbEntry = new DbEntry();
            dbEntry.Id = id;
            dbEntry.Title = title;
            dbEntry.DateFrom = dateFrom;
            dbEntry.UserId = userId;
            return dbEntry;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property DateFrom in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime DateFrom
        {
            get
            {
                return this._DateFrom;
            }
            set
            {
                this.OnDateFromChanging(value);
                this.ReportPropertyChanging("DateFrom");
                this._DateFrom = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateFrom");
                this.OnDateFromChanged();
            }
        }
        private global::System.DateTime _DateFrom;
        partial void OnDateFromChanging(global::System.DateTime value);
        partial void OnDateFromChanged();
        /// <summary>
        /// There are no comments for Property DateTo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateTo
        {
            get
            {
                return this._DateTo;
            }
            set
            {
                this.OnDateToChanging(value);
                this.ReportPropertyChanging("DateTo");
                this._DateTo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateTo");
                this.OnDateToChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateTo;
        partial void OnDateToChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateToChanged();
        /// <summary>
        /// There are no comments for Property ExtensionsData in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtensionsData
        {
            get
            {
                return this._ExtensionsData;
            }
            set
            {
                this.OnExtensionsDataChanging(value);
                this.ReportPropertyChanging("ExtensionsData");
                this._ExtensionsData = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ExtensionsData");
                this.OnExtensionsDataChanged();
            }
        }
        private string _ExtensionsData;
        partial void OnExtensionsDataChanging(string value);
        partial void OnExtensionsDataChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this.ReportPropertyChanging("UserId");
                this._UserId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserId");
                this.OnUserIdChanged();
            }
        }
        private long _UserId;
        partial void OnUserIdChanging(long value);
        partial void OnUserIdChanged();
    }
    /// <summary>
    /// There are no comments for DatabaseModel.DbUser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="DbUser")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class DbUser : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new DbUser object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="password">Initial value of Password.</param>
        public static DbUser CreateDbUser(long id, string name, string password)
        {
            DbUser dbUser = new DbUser();
            dbUser.Id = id;
            dbUser.Name = name;
            dbUser.Password = password;
            return dbUser;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
    }
}
