//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopCalendar.Client.Connector.TopCalendarCommunicationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBaseRequest", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.RegisterUserRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.CheckUserRequest))]
    public partial class UserBaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterUserRequest", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class RegisterUserRequest : TopCalendar.Client.Connector.TopCalendarCommunicationService.UserBaseRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckUserRequest", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class CheckUserRequest : TopCalendar.Client.Connector.TopCalendarCommunicationService.UserBaseRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.RegisterUserResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.CheckUserResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterUserResponse", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class RegisterUserResponse : TopCalendar.Client.Connector.TopCalendarCommunicationService.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckUserResponse", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class CheckUserResponse : TopCalendar.Client.Connector.TopCalendarCommunicationService.BaseResponse {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TopCalendarCommunicationService.ITopCalendarCommunicationService")]
    public interface ITopCalendarCommunicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopCalendarCommunicationService/CheckUser", ReplyAction="http://tempuri.org/ITopCalendarCommunicationService/CheckUserResponse")]
        TopCalendar.Client.Connector.TopCalendarCommunicationService.CheckUserResponse CheckUser(TopCalendar.Client.Connector.TopCalendarCommunicationService.CheckUserRequest checkUserRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopCalendarCommunicationService/RegisterUser", ReplyAction="http://tempuri.org/ITopCalendarCommunicationService/RegisterUserResponse")]
        TopCalendar.Client.Connector.TopCalendarCommunicationService.RegisterUserResponse RegisterUser(TopCalendar.Client.Connector.TopCalendarCommunicationService.RegisterUserRequest registerUserRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ITopCalendarCommunicationServiceChannel : TopCalendar.Client.Connector.TopCalendarCommunicationService.ITopCalendarCommunicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TopCalendarCommunicationServiceClient : System.ServiceModel.ClientBase<TopCalendar.Client.Connector.TopCalendarCommunicationService.ITopCalendarCommunicationService>, TopCalendar.Client.Connector.TopCalendarCommunicationService.ITopCalendarCommunicationService {
        
        public TopCalendarCommunicationServiceClient() {
        }
        
        public TopCalendarCommunicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TopCalendarCommunicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopCalendarCommunicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopCalendarCommunicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TopCalendar.Client.Connector.TopCalendarCommunicationService.CheckUserResponse CheckUser(TopCalendar.Client.Connector.TopCalendarCommunicationService.CheckUserRequest checkUserRequest) {
            return base.Channel.CheckUser(checkUserRequest);
        }
        
        public TopCalendar.Client.Connector.TopCalendarCommunicationService.RegisterUserResponse RegisterUser(TopCalendar.Client.Connector.TopCalendarCommunicationService.RegisterUserRequest registerUserRequest) {
            return base.Channel.RegisterUser(registerUserRequest);
        }
    }
}
