//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopCalendar.Client.Connector.TopCalendarCommunicationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestWithCredentials", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.RegisterUserRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.AddNewTaskRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.FindTasksRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.RemoveTaskRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.LoginUserRequest))]
    public partial class RequestWithCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TopCalendar.Client.Connector.TopCalendarCommunicationService.UserCredentials UserCredentialsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TopCalendar.Client.Connector.TopCalendarCommunicationService.UserCredentials UserCredentials {
            get {
                return this.UserCredentialsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCredentialsField, value) != true)) {
                    this.UserCredentialsField = value;
                    this.RaisePropertyChanged("UserCredentials");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCredentials", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class UserCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterUserRequest", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class RegisterUserRequest : TopCalendar.Client.Connector.TopCalendarCommunicationService.RequestWithCredentials {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddNewTaskRequest", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class AddNewTaskRequest : TopCalendar.Client.Connector.TopCalendarCommunicationService.RequestWithCredentials {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TopCalendar.Client.Connector.TopCalendarCommunicationService.TaskDto TaskField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TopCalendar.Client.Connector.TopCalendarCommunicationService.TaskDto Task {
            get {
                return this.TaskField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskField, value) != true)) {
                    this.TaskField = value;
                    this.RaisePropertyChanged("Task");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FindTasksRequest", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class FindTasksRequest : TopCalendar.Client.Connector.TopCalendarCommunicationService.RequestWithCredentials {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TopCalendar.Client.Connector.TopCalendarCommunicationService.TaskSpecificationDto TaskSpecificationDtoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TopCalendar.Client.Connector.TopCalendarCommunicationService.TaskSpecificationDto TaskSpecificationDto {
            get {
                return this.TaskSpecificationDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskSpecificationDtoField, value) != true)) {
                    this.TaskSpecificationDtoField = value;
                    this.RaisePropertyChanged("TaskSpecificationDto");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoveTaskRequest", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class RemoveTaskRequest : TopCalendar.Client.Connector.TopCalendarCommunicationService.RequestWithCredentials {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaskIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskId {
            get {
                return this.TaskIdField;
            }
            set {
                if ((this.TaskIdField.Equals(value) != true)) {
                    this.TaskIdField = value;
                    this.RaisePropertyChanged("TaskId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginUserRequest", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class LoginUserRequest : TopCalendar.Client.Connector.TopCalendarCommunicationService.RequestWithCredentials {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskDto", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract.Dto")]
    [System.SerializableAttribute()]
    public partial class TaskDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinishAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FinishAt {
            get {
                return this.FinishAtField;
            }
            set {
                if ((this.FinishAtField.Equals(value) != true)) {
                    this.FinishAtField = value;
                    this.RaisePropertyChanged("FinishAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartAt {
            get {
                return this.StartAtField;
            }
            set {
                if ((this.StartAtField.Equals(value) != true)) {
                    this.StartAtField = value;
                    this.RaisePropertyChanged("StartAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskSpecificationDto", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class TaskSpecificationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartAtFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartAtToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartAtFrom {
            get {
                return this.StartAtFromField;
            }
            set {
                if ((this.StartAtFromField.Equals(value) != true)) {
                    this.StartAtFromField = value;
                    this.RaisePropertyChanged("StartAtFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartAtTo {
            get {
                return this.StartAtToField;
            }
            set {
                if ((this.StartAtToField.Equals(value) != true)) {
                    this.StartAtToField = value;
                    this.RaisePropertyChanged("StartAtTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.RegisterUserResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.DataAccessFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.AddNewTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.FindTasksResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.LoginUserResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusReason {
            get {
                return this.StatusReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusReasonField, value) != true)) {
                    this.StatusReasonField = value;
                    this.RaisePropertyChanged("StatusReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterUserResponse", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class RegisterUserResponse : TopCalendar.Client.Connector.TopCalendarCommunicationService.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataAccessFault", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class DataAccessFault : TopCalendar.Client.Connector.TopCalendarCommunicationService.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddNewTaskResponse", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class AddNewTaskResponse : TopCalendar.Client.Connector.TopCalendarCommunicationService.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FindTasksResponse", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class FindTasksResponse : TopCalendar.Client.Connector.TopCalendarCommunicationService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TopCalendar.Client.Connector.TopCalendarCommunicationService.TaskDto[] TasksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TopCalendar.Client.Connector.TopCalendarCommunicationService.TaskDto[] Tasks {
            get {
                return this.TasksField;
            }
            set {
                if ((object.ReferenceEquals(this.TasksField, value) != true)) {
                    this.TasksField = value;
                    this.RaisePropertyChanged("Tasks");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginUserResponse", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
        "Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class LoginUserResponse : TopCalendar.Client.Connector.TopCalendarCommunicationService.BaseResponse {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TopCalendarCommunicationService.ITopCalendarCommunicationService")]
    public interface ITopCalendarCommunicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopCalendarCommunicationService/LoginUser", ReplyAction="http://tempuri.org/ITopCalendarCommunicationService/LoginUserResponse")]
        TopCalendar.Client.Connector.TopCalendarCommunicationService.LoginUserResponse LoginUser(TopCalendar.Client.Connector.TopCalendarCommunicationService.LoginUserRequest loginUserRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopCalendarCommunicationService/RegisterUser", ReplyAction="http://tempuri.org/ITopCalendarCommunicationService/RegisterUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.DataAccessFault), Action="http://tempuri.org/ITopCalendarCommunicationService/RegisterUserDataAccessFaultFa" +
            "ult", Name="DataAccessFault", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
            "Contract.DataContract")]
        TopCalendar.Client.Connector.TopCalendarCommunicationService.RegisterUserResponse RegisterUser(TopCalendar.Client.Connector.TopCalendarCommunicationService.RegisterUserRequest registerUserRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopCalendarCommunicationService/AddNewTask", ReplyAction="http://tempuri.org/ITopCalendarCommunicationService/AddNewTaskResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.DataAccessFault), Action="http://tempuri.org/ITopCalendarCommunicationService/AddNewTaskDataAccessFaultFaul" +
            "t", Name="DataAccessFault", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
            "Contract.DataContract")]
        TopCalendar.Client.Connector.TopCalendarCommunicationService.AddNewTaskResponse AddNewTask(TopCalendar.Client.Connector.TopCalendarCommunicationService.AddNewTaskRequest addNewTaskRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopCalendarCommunicationService/FindTasks", ReplyAction="http://tempuri.org/ITopCalendarCommunicationService/FindTasksResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.DataAccessFault), Action="http://tempuri.org/ITopCalendarCommunicationService/FindTasksDataAccessFaultFault" +
            "", Name="DataAccessFault", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
            "Contract.DataContract")]
        TopCalendar.Client.Connector.TopCalendarCommunicationService.FindTasksResponse FindTasks(TopCalendar.Client.Connector.TopCalendarCommunicationService.FindTasksRequest findTasksRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopCalendarCommunicationService/RemoveTask", ReplyAction="http://tempuri.org/ITopCalendarCommunicationService/RemoveTaskResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TopCalendar.Client.Connector.TopCalendarCommunicationService.DataAccessFault), Action="http://tempuri.org/ITopCalendarCommunicationService/RemoveTaskDataAccessFaultFaul" +
            "t", Name="DataAccessFault", Namespace="http://schemas.datacontract.org/2004/07/TopCalendar.Server.ServiceLibrary.Service" +
            "Contract.DataContract")]
        TopCalendar.Client.Connector.TopCalendarCommunicationService.BaseResponse RemoveTask(TopCalendar.Client.Connector.TopCalendarCommunicationService.RemoveTaskRequest deleteTaskRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ITopCalendarCommunicationServiceChannel : TopCalendar.Client.Connector.TopCalendarCommunicationService.ITopCalendarCommunicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TopCalendarCommunicationServiceClient : System.ServiceModel.ClientBase<TopCalendar.Client.Connector.TopCalendarCommunicationService.ITopCalendarCommunicationService>, TopCalendar.Client.Connector.TopCalendarCommunicationService.ITopCalendarCommunicationService {
        
        public TopCalendarCommunicationServiceClient() {
        }
        
        public TopCalendarCommunicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TopCalendarCommunicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopCalendarCommunicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopCalendarCommunicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TopCalendar.Client.Connector.TopCalendarCommunicationService.LoginUserResponse LoginUser(TopCalendar.Client.Connector.TopCalendarCommunicationService.LoginUserRequest loginUserRequest) {
            return base.Channel.LoginUser(loginUserRequest);
        }
        
        public TopCalendar.Client.Connector.TopCalendarCommunicationService.RegisterUserResponse RegisterUser(TopCalendar.Client.Connector.TopCalendarCommunicationService.RegisterUserRequest registerUserRequest) {
            return base.Channel.RegisterUser(registerUserRequest);
        }
        
        public TopCalendar.Client.Connector.TopCalendarCommunicationService.AddNewTaskResponse AddNewTask(TopCalendar.Client.Connector.TopCalendarCommunicationService.AddNewTaskRequest addNewTaskRequest) {
            return base.Channel.AddNewTask(addNewTaskRequest);
        }
        
        public TopCalendar.Client.Connector.TopCalendarCommunicationService.FindTasksResponse FindTasks(TopCalendar.Client.Connector.TopCalendarCommunicationService.FindTasksRequest findTasksRequest) {
            return base.Channel.FindTasks(findTasksRequest);
        }
        
        public TopCalendar.Client.Connector.TopCalendarCommunicationService.BaseResponse RemoveTask(TopCalendar.Client.Connector.TopCalendarCommunicationService.RemoveTaskRequest deleteTaskRequest) {
            return base.Channel.RemoveTask(deleteTaskRequest);
        }
    }
}
